import InteractivePattern from "../../components/InteractivePattern/index.jsx";

const exampleData = [
  [
    { type: "P", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "P", width: 1 },
  ],
  //   [
  //     { type: "P" },
  //     { type: "P" },
  //     { type: "CF", connectedR: true },
  //     { type: "CF", connectedR: true, connectedL: true },
  //     { type: "CF", connectedR: true, connectedL: true },
  //     { type: "CF", connectedL: true },
  //     { type: "CB", connectedR: true },
  //     { type: "CB", connectedR: true, connectedL: true },
  //     { type: "CB", connectedR: true, connectedL: true },
  //     { type: "CB", connectedL: true },
  //     { type: "P" },
  //     { type: "P" },
  //   ],
  [
    { type: "P", width: 1 },
    { type: "P", width: 1 },
    { type: "CF", width: 4 },
    { type: "CB", width: 4 },
    { type: "P", width: 1 },
    { type: "P", width: 1 },
  ],
  [
    { type: "P", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "P", width: 1 },
  ],
  [
    { type: "P", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "P", width: 1 },
  ],
];

const exampleDataTwo = [
  [
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
  ],
  [
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "CB", width: 6 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
  ],
  [
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
  ],
  [
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
  ],
  [
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
  ],
  [
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "CF", width: 6 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
  ],
  [
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
  ],
  [
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "P", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
    { type: "K", width: 1 },
  ],
];

export default function PatternScreen() {
  return (
    <div>
      <InteractivePattern data={exampleData} />
      <InteractivePattern data={exampleDataTwo} />
    </div>
  );
}
